inherit_from:
  - https://raw.githubusercontent.com/pixta-dev/pixta-rubocop/master/rubocop.yml

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'db/**/*'
    - 'deploy/**/*'
    - 'frontend/**/*'
    - 'admin/vendor/**/*'
    - 'admin/bin/*'
    - 'admin/config/**/*'
    - 'admin/Gemfile'
    - 'admin/db/**/*'
    - 'admin/lib/admin/version.rb'
    - 'admin/lib/admin/engine.rb'
